module.exports = 
{
    'Albania Lek'								: { abbreviation: 'ALL', number_code: '008'},
    'Afghanistan Afghani'						: { abbreviation: 'AFA', number_code: '004'},
    'Argentina Peso'							: { abbreviation: 'ARS', number_code: '032'},
    'Aruba Guilder'								: { abbreviation: 'AWG', number_code: '533'},
    'Australia Dollar'							: { abbreviation: 'AUD', number_code: '036'},
    'Azerbaijan New Manat'						: { abbreviation: 'AZM', number_code: '031'},
    'Bahamas Dollar'							: { abbreviation: 'BSD', number_code: '044'},
    'Barbados Dollar'							: { abbreviation: 'BBD', number_code: '052'},
    'Bangladeshi taka'							: { abbreviation: 'BDT', number_code: '050'},
    'Belarus Ruble'								: { abbreviation: 'BYR', number_code: '974'},
    'Belize Dollar'								: { abbreviation: 'BZD', number_code: '084'},
    'Bermuda Dollar'							: { abbreviation: 'BMD', number_code: '060'},
    'Bolivia Boliviano'							: { abbreviation: 'BOB', number_code: '068'},
    'Bosnia and Herzegovina Convertible Marka'	: { abbreviation: 'BAM', number_code: '977'},
    'Botswana Pula'								: { abbreviation: 'BWP', number_code: '072'},
    'Bulgaria Lev'								: { abbreviation: 'BGN', number_code: '975'},
    'Brazil Real'								: { abbreviation: 'BRL', number_code: '986'},
    'Brunei Darussalam Dollar'					: { abbreviation: 'BND', number_code: '096'},
    'Cambodia Riel'								: { abbreviation: 'KHR', number_code: '116'},
    'Canada Dollar'								: { abbreviation: 'CAD', number_code: '124'},
    'Cayman Islands Dollar'						: { abbreviation: 'KYD', number_code: '136'},
    'Chilean Peso'								: { abbreviation: 'CLP', number_code: '152'},
    'China Yuan Renminbi'						: { abbreviation: 'CNY', number_code: '156'},
    'Colombia Peso'								: { abbreviation: 'COP', number_code: '170'},
    'Costa Rican Colon'							: { abbreviation: 'CRC', number_code: '188'},
    'Croatian Kuna'								: { abbreviation: 'HRK', number_code: '191'},
    'Cuban Peso'								: { abbreviation: 'CUP', number_code: '192'},
    'Czech Republic Koruna'						: { abbreviation: 'CZK', number_code: '203'},
    'Denmark Krone'								: { abbreviation: 'DKK', number_code: '208'},
    'Dominican Republic Peso'					: { abbreviation: 'DOP', number_code: '214'},
    'East Caribbean Dollar'						: { abbreviation: 'XCD', number_code: '951'},
    'Egypt Pound'								: { abbreviation: 'EGP', number_code: '818'},
    'El Salvador Colon'							: { abbreviation: 'SVC', number_code: '222'},
    'Estonia Kroon'								: { abbreviation: 'EEK', number_code: '233'},
    'Euro Member Countries'						: { abbreviation: 'EUR', number_code: '978'},
    'Falkland Islands (Malvinas) Pound'			: { abbreviation: 'FKP', number_code: '238'},
    'Fiji Dollar'								: { abbreviation: 'FJD', number_code: '242'},
    'Ghana Cedis'								: { abbreviation: 'GHC', number_code: '288'},
    'Gibraltar Pound'							: { abbreviation: 'GIP', number_code: '292'},
    'Guatemala Quetzal'							: { abbreviation: 'GTQ', number_code: '320'},
    'Guernsey Pound'							: { abbreviation: 'GGP', number_code: '831'},
    'Guyana Dollar'								: { abbreviation: 'GYD', number_code: '328'},
    'Honduras Lempira'							: { abbreviation: 'HNL', number_code: '340'},
    'Hong Kong Dollar'							: { abbreviation: 'HKD', number_code: '344'},
    'Hungary Forint'							: { abbreviation: 'HUF', number_code: '348'},
    'Iceland Krona'								: { abbreviation: 'ISK', number_code: '352'},
    'India Rupee'								: { abbreviation: 'INR', number_code: '356'},
    'Indonesia Rupiah'							: { abbreviation: 'IDR', number_code: '360'},
    'Iran Rial'									: { abbreviation: 'IRR', number_code: '364'},
    'Isle of Man Pound'							: { abbreviation: 'IMP', number_code: '833'},
    'Israel Shekel'								: { abbreviation: 'ILS', number_code: '376'},
    'Jamaica Dollar'							: { abbreviation: 'JMD', number_code: '388'},
    'Japan Yen'									: { abbreviation: 'JPY', number_code: '392'},
    'Jersey Pound'								: { abbreviation: 'JEP', number_code: '832'},
    'Kazakhstan Tenge'							: { abbreviation: 'KZT', number_code: '398'},
    'Korea (North) Won'							: { abbreviation: 'KPW', number_code: '408'},
    'Korea (South) Won'							: { abbreviation: 'KRW', number_code: '410'},
    'Kyrgyzstan Som'							: { abbreviation: 'KGS', number_code: '417'},
    'Laos Kip'									: { abbreviation: 'LAK', number_code: '418'},
    'Latvia Lat'								: { abbreviation: 'LVL', number_code: '428'},
    'Lebanon Pound'								: { abbreviation: 'LBP', number_code: '422'},
    'Liberia Dollar'							: { abbreviation: 'LRD', number_code: '430'},
    'Lithuania Litas'							: { abbreviation: 'LTL', number_code: '440'},
    'Macedonia Denar'							: { abbreviation: 'MKD', number_code: '807'},
    'Malaysia Ringgit'							: { abbreviation: 'MYR', number_code: '458'},
    'Mauritius Rupee'							: { abbreviation: 'MUR', number_code: '480'},
    'Mexico Peso'								: { abbreviation: 'MXN', number_code: '484'},
    'Mongolia Tughrik'							: { abbreviation: 'MNT', number_code: '496'},
    'Mozambique Metical'						: { abbreviation: 'MZM', number_code: '508'},
    'Namibia Dollar'							: { abbreviation: 'ALL', number_code: '516'},
    'Nepal Rupee'								: { abbreviation: 'NPR', number_code: '524'},
    'Netherlands Antilles Guilder'				: { abbreviation: 'ANG', number_code: '532'},
    'New Zealand Dollar'						: { abbreviation: 'NZD', number_code: '554'},
    'Nicaragua Cordoba'							: { abbreviation: 'NIO', number_code: '558'},
    'Nigeria Naira'								: { abbreviation: 'NGN', number_code: '566'},
    'Norway Krone'								: { abbreviation: 'NOK', number_code: '578'},
    'Oman Rial'									: { abbreviation: 'OMR', number_code: '512'},
    'Pakistan Rupee'							: { abbreviation: 'PKR', number_code: '856'},
    'Panama Balboa'								: { abbreviation: 'PAB', number_code: '590'},
    'Paraguay Guarani'							: { abbreviation: 'PYG', number_code: '600'},
    'Peru Nuevo Sol'							: { abbreviation: 'PEN', number_code: '604'},
    'Philippines Peso'							: { abbreviation: 'PHP', number_code: '608'},
    'Poland Zloty'								: { abbreviation: 'PLN', number_code: '985'},
    'Qatar Riyal'								: { abbreviation: 'QAR', number_code: '634'},
    'Romania New Leu'							: { abbreviation: 'ROL', number_code: '642'},
    'Russia Ruble'								: { abbreviation: 'RUB', number_code: '643'},
    'Saint Helena Pound'						: { abbreviation: 'SHP', number_code: '654'},
    'Saudi Arabia Riyal'						: { abbreviation: 'SAR', number_code: '682'},
    'Serbia Dinar'								: { abbreviation: 'RSD', number_code: '941'},
    'Seychelles Rupee'							: { abbreviation: 'SCR', number_code: '690'},
    'Singapore Dollar'							: { abbreviation: 'SGD', number_code: '702'},
    'Solomon Islands Dollar'					: { abbreviation: 'SBD', number_code: '090'},
    'Somalia Shilling'							: { abbreviation: 'SOS', number_code: '706'},
    'South Africa Rand'							: { abbreviation: 'ZAR', number_code: '710'},
    'Sri Lanka Rupee'							: { abbreviation: 'LKR', number_code: '144'},
    'Sweden Krona'								: { abbreviation: 'SEK', number_code: '752'},
    'Switzerland Franc'							: { abbreviation: 'CHF', number_code: '756'},
    'Suriname Dollar'							: { abbreviation: 'SRD', number_code: '740'},
    'Syria Pound'								: { abbreviation: 'SYP', number_code: '760'},
    'Taiwan New Dollar'							: { abbreviation: 'TWD', number_code: '901'},
    'Thailand Baht'								: { abbreviation: 'THB', number_code: '764'},
    'Trinidad and Tobago Dollar'				: { abbreviation: 'TTD', number_code: '780'},
    'Turkey Lira'								: { abbreviation: 'TRY', number_code: '949'},
    'Tuvalu Dollar'								: { abbreviation: 'TVD', number_code: '798'},
    'Ukraine Hryvna'							: { abbreviation: 'UAH', number_code: '980'},
    'United Kingdom Pound'					    : { abbreviation: 'GBP', number_code: '826'},
    'Uganda Shilling'							: { abbreviation: 'UGX', number_code: '800'},
    'United States Dollar'						: { abbreviation: 'USD', number_code: '840'},
    'Uruguay Peso'								: { abbreviation: 'UYU', number_code: '858'},
    'Uzbekistan Som'							: { abbreviation: 'UZS', number_code: '860'},
    'Venezuela Bolivar'							: { abbreviation: 'VEF', number_code: '937'},
    'Viet Nam Dong'								: { abbreviation: 'VND', number_code: '704'},
    'Yemen Rial'								: { abbreviation: 'YER', number_code: '886'},
    'Zimbabwe Dollar'							: { abbreviation: 'ZWD', number_code: '716'},
}